services:
  backend:
    build: ./backend
    env_file: ./backend/.env
    volumes:
      - db_data:/app/db
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1

  frontend:
    build: ./frontend
    expose:
      - "80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
