import React, { useState } from "react"
import { Play, Pause, Sparkles, ChevronRight, Mic, Sliders, Volume2, ShieldCheck } from "lucide-react"

export function Hero({ onOpenStudio }) {
  const [isPlaying, setIsPlaying] = useState(false)
  const [activeVoice, setActiveVoice] = useState("Rachel")
  const [speed, setSpeed] = useState(1.0)

  const voices = [
    { name: "Rachel", tag: "Expressive Conversational", accent: "American", gender: "Female" },
    { name: "Adam", tag: "Deep Narrative", accent: "American", gender: "Male" },
    { name: "Domi", tag: "Energetic & Bold", accent: "British", gender: "Female" },
    { name: "Antoni", tag: "Warm & Editorial", accent: "American", gender: "Male" },
  ]

  return (
    <section className="relative w-full py-16 md:py-24 px-4 md:px-8 bg-[#f5f5f5] overflow-hidden">
      {/* Background Atmospheric Gradient Orb (Signature Bloom) */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[700px] h-[500px] orb-hero-bloom blur-3xl pointer-events-none opacity-80" />

      <div className="max-w-[1200px] mx-auto relative z-10 space-y-12">
        
        {/* Editorial Headline & Lead */}
        <div className="max-w-4xl mx-auto text-center space-y-6">
          {/* Section Badge */}
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#f0efed] border border-[#e7e5e4] text-[#0c0a09] text-xs uppercase tracking-[0.96px] font-semibold">
            <Sparkles className="w-3.5 h-3.5 text-[#292524]" />
            <span>Generative Voice & Agent Architecture</span>
          </div>

          {/* Main Display Headline (EB Garamond Light 300 @ 64px) */}
          <h1 className="font-serif font-light text-4xl sm:text-5xl md:text-6xl lg:text-[64px] text-[#0c0a09] tracking-[-1.92px] leading-[1.05]">
            Human quality audio, generated by artificial intelligence.
          </h1>

          {/* Editorial Body Subtitle (Inter 400 @ 16px tracking +0.16px) */}
          <p className="text-base sm:text-lg text-[#4e4e4e] max-w-2xl mx-auto leading-relaxed tracking-[0.16px]">
            Convert text into natural speech with lifelike cadence, emotional expression, and real-time execution loops across 32 languages.
          </p>

          {/* CTAs */}
          <div className="flex flex-wrap items-center justify-center gap-4 pt-2">
            {/* Primary Near-black Ink Pill */}
            <button
              onClick={onOpenStudio}
              className="px-6 py-3 rounded-full bg-[#292524] text-white hover:bg-[#0c0a09] font-medium text-[15px] shadow-xs transition-all flex items-center gap-2"
            >
              <span>Launch Agent Studio</span>
              <ChevronRight className="w-4 h-4 text-white/80" />
            </button>

            {/* Secondary Transparent Outline Pill */}
            <a
              href="#voices"
              className="px-6 py-3 rounded-full bg-transparent text-[#0c0a09] border border-[#d6d3d1] hover:bg-[#f0efed] hover:border-[#0c0a09] font-medium text-[15px] transition-all"
            >
              Explore Voice Library
            </a>
          </div>
        </div>

        {/* Audio Waveform Card Preview Component */}
        <div className="max-w-3xl mx-auto bg-[#ffffff] border border-[#e7e5e4] rounded-2xl p-6 sm:p-8 shadow-soft-drop space-y-6">
          
          {/* Card Header & Voice Selectors */}
          <div className="flex flex-wrap items-center justify-between gap-4 pb-4 border-b border-[#f0efed]">
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 rounded-full bg-[#f0efed] flex items-center justify-center text-[#0c0a09] font-medium text-xs">
                {activeVoice[0]}
              </div>
              <div>
                <h4 className="text-sm font-semibold text-[#0c0a09] flex items-center gap-2">
                  {activeVoice}
                  <span className="text-[10px] font-normal uppercase tracking-wider px-2 py-0.5 rounded-full bg-[#f0efed] text-[#4e4e4e]">
                    24kHz HD
                  </span>
                </h4>
                <p className="text-xs text-[#777169]">
                  {voices.find(v => v.name === activeVoice)?.tag} · {voices.find(v => v.name === activeVoice)?.accent}
                </p>
              </div>
            </div>

            {/* Voice Pill Selector */}
            <div className="flex items-center gap-1.5 bg-[#f5f5f5] p-1 rounded-full border border-[#e7e5e4]">
              {voices.map(v => (
                <button
                  key={v.name}
                  onClick={() => setActiveVoice(v.name)}
                  className={`px-3 py-1 rounded-full text-xs font-medium transition-all ${
                    activeVoice === v.name
                      ? "bg-[#292524] text-white shadow-xs"
                      : "text-[#4e4e4e] hover:text-[#0c0a09]"
                  }`}
                >
                  {v.name}
                </button>
              ))}
            </div>
          </div>

          {/* Interactive Text Display */}
          <div className="p-4 rounded-xl bg-[#fafafa] border border-[#e7e5e4] font-serif text-lg text-[#292524] leading-relaxed italic">
            "In a world where digital presence requires authentic expression, synthetic voice reaches the emotional threshold of human storytelling."
          </div>

          {/* Waveform Visualization & Player Controls */}
          <div className="flex items-center justify-between gap-4 pt-2">
            <button
              onClick={() => setIsPlaying(!isPlaying)}
              className="w-12 h-12 rounded-full bg-[#292524] hover:bg-[#0c0a09] text-white flex items-center justify-center shadow-xs transition-all flex-shrink-0"
              title={isPlaying ? "Pause audio" : "Play sample"}
            >
              {isPlaying ? <Pause className="w-5 h-5 fill-current" /> : <Play className="w-5 h-5 fill-current ml-0.5" />}
            </button>

            {/* Dynamic Waveform Bars */}
            <div className="flex-1 h-12 flex items-center justify-between gap-1 px-2">
              {[40, 65, 30, 85, 95, 60, 45, 75, 90, 100, 70, 50, 80, 65, 35, 90, 75, 40, 60, 85, 95, 50, 30, 70, 90, 45, 60, 80, 55, 35].map((height, i) => (
                <span
                  key={i}
                  className={`w-1 rounded-full transition-all duration-300 ${
                    isPlaying
                      ? "bg-[#0c0a09] animate-pulse"
                      : i < 12
                      ? "bg-[#292524]"
                      : "bg-[#e7e5e4]"
                  }`}
                  style={{
                    height: isPlaying ? `${Math.max(15, (height * Math.random()).toFixed(0))}%` : `${height}%`,
                    animationDelay: `${i * 40}ms`
                  }}
                />
              ))}
            </div>

            {/* Metadata indicator */}
            <div className="hidden sm:flex items-center gap-2 text-xs font-mono text-[#777169] bg-[#f0efed] px-3 py-1.5 rounded-full">
              <Volume2 className="w-3.5 h-3.5 text-[#0c0a09]" />
              <span>1.0x · 24000 Hz</span>
            </div>
          </div>

        </div>

      </div>
    </section>
  )
}
