"""Input guardrail — LLM-judge that runs before the planner loop.

Classifies whether the user's message is within the system's scope
(real estate listings and marketing campaigns data only). Uses a
separate, smaller model (`GUARDRAIL_MODEL`) to minimise added latency.

The judge does a *pure classification* only — a boolean plus a small
category enum. It never generates free text: a small/fast model asked to
write a refusal message reliably falls into a token-repetition loop
(observed with `llama-3.1-8b-instant` producing runaway Arabic text until
it exhausts its token budget, which Groq then rejects as
`tool_use_failed`). The refusal message is instead built deterministically
in `_refusal_message`, which also picks the user's language by script.

Fails open: if the judge call errors, the request is allowed through to
the planner, which is itself scope-constrained by the system prompt.
"""

from __future__ import annotations

from dataclasses import dataclass

from app.agent.llm_client import LLMCallError, call_llm
from app.utilities.logging_utils import log_guardrail_event
from config.settings import settings

_SYSTEM_PROMPT = """\
You are a scope classifier for a real estate and marketing analytics data assistant.
The assistant can ONLY help with:
- The real_estate_listings table (querying/inserting/updating/deleting listings)
- The marketing_campaigns table (querying/inserting/updating/deleting campaigns)
- Questions about the data in those two tables

Everything else is OUT OF SCOPE: cooking, general knowledge, coding help, weather,
math, creative writing, and any topic not directly about those two tables.

Call `classify_scope` exactly once. Do NOT write any prose or explanation —
only set `in_scope` and `category`.

Examples:
- "Which listings are active in Cairo?" -> in_scope: true, category: real_estate
- "Show me Facebook campaigns" -> in_scope: true, category: marketing
- "كيف أطبخ الأرز واللحم؟" -> in_scope: false, category: out_of_scope
- "What is the capital of France?" -> in_scope: false, category: out_of_scope
"""

_CLASSIFY_TOOL = {
    "name": "classify_scope",
    "description": "Classify whether the user message is within the assistant's scope.",
    "parameters": {
        "type": "object",
        "properties": {
            "in_scope": {
                "type": "boolean",
                "description": "True if the message is about real estate listings or marketing campaigns data.",
            },
            "category": {
                "type": "string",
                "enum": ["real_estate", "marketing", "both", "out_of_scope"],
                "description": "Which data domain the message concerns, or out_of_scope.",
            },
        },
        "required": ["in_scope", "category"],
    },
}

# Deterministic refusals — never generated by the model (see module docstring).
_REFUSAL_EN = (
    "I can only help with real estate listings and marketing campaigns data. "
    "Please ask a question about those."
)
_REFUSAL_AR = (
    "يمكنني فقط المساعدة في بيانات العقارات والحملات التسويقية. "
    "من فضلك اطرح سؤالاً عن ذلك."
)


def _refusal_message(user_message: str) -> str:
    """Pick the refusal language by script: Arabic input -> Arabic refusal.

    Uses the Arabic Unicode block (U+0600–U+06FF) rather than an LLM call,
    so the refusal is deterministic, testable, and can't loop."""
    if any("؀" <= ch <= "ۿ" for ch in user_message):
        return _REFUSAL_AR
    return _REFUSAL_EN


@dataclass
class GuardrailDecision:
    allowed: bool
    message: str = ""


def check_scope(user_message: str, request_id: str) -> GuardrailDecision:
    """Return GuardrailDecision(allowed=True) to proceed, or (allowed=False, message=...)
    to short-circuit with a refusal. Fails open on any LLM error."""
    messages = [
        {"role": "system", "content": _SYSTEM_PROMPT},
        {"role": "user", "content": user_message},
    ]
    try:
        response = call_llm(
            messages=messages,
            tools=[_CLASSIFY_TOOL],
            model=settings.guardrail_model,
            loop_iteration=0,
            request_id=request_id,
        )
        if response.tool_calls:
            args = response.tool_calls[0].get("args", {})
            in_scope = bool(args.get("in_scope", True))
            log_guardrail_event(
                request_id=request_id, allowed=in_scope, model=settings.guardrail_model
            )
            if in_scope:
                return GuardrailDecision(allowed=True)
            return GuardrailDecision(allowed=False, message=_refusal_message(user_message))
        # No tool call at all — treat as inconclusive and fail open.
        log_guardrail_event(
            request_id=request_id,
            allowed=True,
            model=settings.guardrail_model,
            error="no_tool_call",
        )
    except LLMCallError:
        # Fail open: a guardrail error must never block legitimate users.
        log_guardrail_event(
            request_id=request_id,
            allowed=True,
            model=settings.guardrail_model,
            error="guardrail_llm_error",
        )
    return GuardrailDecision(allowed=True)
